//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glampinho
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alojamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alojamento()
        {
            this.EstAlojExtra = new HashSet<EstAlojExtra>();
        }
    
        public string nome { get; set; }
        public string parque { get; set; }
        public string localizacao { get; set; }
        public string descricao { get; set; }
        public decimal precoBase { get; set; }
        public int nMaxPessoas { get; set; }
        public string tipo { get; set; }
    
        public virtual ParqueCampismo ParqueCampismo { get; set; }
        public virtual Bungalows Bungalows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstAlojExtra> EstAlojExtra { get; set; }
        public virtual HistoricoAloj HistoricoAloj { get; set; }
        public virtual Tendas Tendas { get; set; }
    }
}
