//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glampinho
{
    using System;
    using System.Collections.Generic;
    
    public partial class BungalowView
    {
        public string nomeCamp { get; set; }
        public string morada { get; set; }
        public int estrelas { get; set; }
        public string mail { get; set; }
        public string nomeAloj { get; set; }
        public string localizacao { get; set; }
        public string descricao { get; set; }
        public decimal precoBase { get; set; }
        public int nMaxPessoas { get; set; }
    }
}
