//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glampinho
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstAlojExtra
    {
        public int id { get; set; }
        public string alojamento { get; set; }
        public int extra { get; set; }
    
        public virtual Alojamento Alojamento1 { get; set; }
        public virtual Estada Estada { get; set; }
        public virtual Extra Extra1 { get; set; }
    }
}
