//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glampinho
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoExtra
    {
        public int extra { get; set; }
        public System.DateTime dataInicial { get; set; }
        public decimal preco { get; set; }
    
        public virtual Extra Extra1 { get; set; }
    }
}
